import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, LockKeyhole, Mountain } from "lucide-react";
import { FormEvent, useEffect } from "react";
import { useLocation } from "wouter";

export default function AdminSetup() { const [, setLocation] = useLocation(); const { data, isLoading } = trpc.adminAuth.setupStatus.useQuery(); const setup = trpc.adminAuth.setupPrincipal.useMutation(); useEffect(() => { if (!isLoading && !data?.needsSetup) setLocation("/admin/login"); }, [data, isLoading, setLocation]); function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setup.mutate({ name: String(form.get("name")), email: String(form.get("email")), password: String(form.get("password")) }, { onSuccess: () => setLocation("/admin/login") }); } return <main className="grid min-h-screen place-items-center bg-[#eef4f2] px-4 py-10"><div className="w-full max-w-md overflow-hidden rounded-[1.5rem] border border-[#d7e3de] bg-white shadow-[0_28px_70px_rgba(18,61,91,.15)]"><div className="bg-[#123d5b] p-7 text-white"><span className="grid size-11 place-items-center rounded-xl bg-[#f39a48] text-[#123d5b]"><Mountain className="size-5" /></span><p className="mt-5 text-xs font-extrabold uppercase tracking-[.14em] text-[#f39a48]">First-time setup</p><h1 className="display mt-2 text-4xl font-bold">Set the principal admin.</h1><p className="mt-3 text-sm leading-6 text-white/70">This protected, one-time step creates the account that can manage all other administrators.</p></div>{isLoading ? <div className="p-8 text-sm text-slate-500">Checking secure setup status…</div> : data?.needsSetup ? <form onSubmit={submit} className="p-7"><div className="grid gap-5"><Field label="Your name" name="name" /><Field label="Administrator email" name="email" type="email" /><div><Label htmlFor="password">Create a strong password</Label><Input id="password" className="mt-2 h-11" name="password" type="password" minLength={12} autoComplete="new-password" required /><p className="mt-2 text-xs leading-5 text-slate-500">Use 12 or more characters. This account becomes the principal administrator.</p></div></div><Button disabled={setup.isPending} className="mt-7 h-12 w-full rounded-xl bg-[#e9781c] text-xs font-extrabold uppercase tracking-[.1em] hover:bg-[#d86b12]">{setup.isPending ? "Creating account…" : "Create principal admin"}</Button>{setup.error && <p className="mt-4 text-sm text-red-600">{setup.error.message}</p>}</form> : <div className="p-8 text-center"><CheckCircle2 className="mx-auto size-10 text-[#2d9b61]" /><p className="mt-4 text-sm text-slate-600">The principal admin is already configured.</p></div>}</div></main>; }
function Field({ label, name, type = "text" }: { label: string; name: string; type?: string }) { return <div><Label htmlFor={name}>{label}</Label><Input id={name} className="mt-2 h-11" name={name} type={type} autoComplete={type === "email" ? "email" : "name"} required /></div>; }
