import PublicLayout from "@/components/PublicLayout";
import TourCard from "@/components/TourCard";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BadgeCheck, CalendarDays, CheckCircle2, Compass, HeartHandshake, Landmark, MapPinned, Mountain, Search, ShieldCheck, Star, TentTree, UsersRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useLocation } from "wouter";

const experiences = [
  { title: "Trekking", filter: "Trekking", icon: Mountain, image: "/manus-storage/triund-hikers_7653a06a.jpg", copy: "Guided ridge walks, planned at a sensible pace." },
  { title: "Local culture", filter: "Experiences", icon: Landmark, image: "/manus-storage/dharamshala-prayer-flags_26329188.jpg", copy: "Dharamshala stories, food and places with context." },
  { title: "Adventure", filter: "Adventure", icon: TentTree, image: "/manus-storage/triund-camp_ded436f5.jpg", copy: "Camping and mountain days for active groups." },
  { title: "All journeys", filter: "All", icon: Compass, image: "/manus-storage/dharamshala-valley_971eee0a.jpg", copy: "Browse every current trip in one place." },
];

export default function Home() {
  const { data: tours = [] } = trpc.tours.featured.useQuery();
  const { data: reviews = [] } = trpc.reviews.list.useQuery(undefined, { retry: false });
  const [, setLocation] = useLocation();
  const [query, setQuery] = useState("");
  const newsletter = trpc.newsletter.subscribe.useMutation();
  const enquiry = trpc.enquiries.create.useMutation();
  const [email, setEmail] = useState("");
  const [enquirySent, setEnquirySent] = useState(false);
  function search(event: FormEvent) { event.preventDefault(); if (query.trim()) setLocation(`/search?q=${encodeURIComponent(query.trim())}`); }
  function subscribe(event: FormEvent) { event.preventDefault(); newsletter.mutate({ email }, { onSuccess: () => setEmail("") }); }
  function sendEnquiry(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); enquiry.mutate({ name: String(form.get("name")), email: String(form.get("email")), phone: String(form.get("phone")) || undefined, subject: "Homepage trip enquiry", message: String(form.get("message")) }, { onSuccess: () => setEnquirySent(true) }); }
  return <PublicLayout>
    <section className="relative isolate min-h-[680px] overflow-hidden bg-[#0e3d5c] text-white lg:min-h-[730px]">
      <img src="/manus-storage/dharamshala-valley_971eee0a.jpg" alt="Dhauladhar views above Dharamshala" className="absolute inset-0 h-full w-full object-cover" fetchPriority="high" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,39,61,.91)_0%,rgba(7,39,61,.7)_42%,rgba(7,39,61,.14)_100%)]" /><div className="absolute inset-x-0 bottom-0 h-44 bg-gradient-to-t from-[#0b3553] to-transparent" />
      <div className="container relative flex min-h-[680px] flex-col justify-center py-24 lg:min-h-[730px]">
        <div className="max-w-3xl"><p className="rise text-xs font-extrabold uppercase tracking-[.16em] text-[#f6a85c]">Trip Himalaya · Dharamshala, Himachal Pradesh</p><h1 className="rise-2 mt-5 max-w-2xl font-display text-[clamp(2.85rem,6.5vw,5.45rem)] font-bold leading-[.96] tracking-[-.045em]">Dharamshala journeys, planned with local care.</h1><p className="rise-3 mt-6 max-w-xl text-base leading-7 text-white/82 sm:text-lg">Treks, stays and useful local experiences—planned around your dates, pace and group.</p></div>
        <div className="rise-3 mt-8 flex flex-wrap gap-3"><Link href="/tours" className="focus-ring inline-flex h-12 items-center gap-2 rounded-lg bg-[#e9781c] px-5 text-xs font-extrabold uppercase tracking-[.09em] text-white shadow-lg shadow-black/15 transition hover:bg-[#d86b12] active:scale-[.97]">Explore tours <ArrowRight className="size-4" /></Link><Link href="/contact" className="focus-ring inline-flex h-12 items-center gap-2 rounded-lg border border-white/45 bg-white/10 px-5 text-xs font-extrabold uppercase tracking-[.09em] text-white transition hover:bg-white/20 active:scale-[.97]"><CalendarDays className="size-4" /> Plan your trip</Link></div>
        <form onSubmit={search} className="rise-3 mt-10 grid max-w-3xl gap-2 rounded-xl border border-white/20 bg-[#123d5b]/65 p-2.5 backdrop-blur-md sm:grid-cols-[1fr_auto]" role="search"><label className="sr-only" htmlFor="hero-search">Search trips</label><div className="flex items-center gap-3 px-3"><Search className="size-5 shrink-0 text-[#f5a653]" /><input id="hero-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search Triund, Bir or a type of journey" className="h-11 min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-white/58" /></div><button className="focus-ring h-11 rounded-lg bg-white px-6 text-xs font-extrabold uppercase tracking-[.09em] text-[#123d5b] transition hover:bg-[#f7f1e8] active:scale-[.97]">Search trips</button></form>
      </div>
      <div className="relative border-t border-white/14 bg-[#0b3553]/92 backdrop-blur"><div className="container grid divide-y divide-white/12 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4">{[[UsersRound, "Dharamshala team", "Local planning from people based here."], [BadgeCheck, "Clear before booking", "Useful details, dates and pricing up front."], [ShieldCheck, "Prepared for the route", "Guidance shaped around mountain conditions."], [HeartHandshake, "Direct support", "A real point of contact before and during travel."]].map(([Icon, title, copy]) => <div key={String(title)} className="flex items-center gap-3 px-3 py-4 sm:px-5"><Icon className="size-5 shrink-0 text-[#f39a48]" /><span><strong className="block text-xs font-extrabold uppercase tracking-[.06em]">{String(title)}</strong><span className="mt-1 block text-xs text-white/65">{String(copy)}</span></span></div>)}</div></div>
    </section>
    <section className="mountain-grid py-20 sm:py-24"><div className="container"><div className="grid gap-5 lg:grid-cols-[1fr_.72fr] lg:items-end"><div><p className="eyebrow">Explore Himachal your way</p><h2 className="section-title mt-3 normal-case tracking-[-.03em]">Choose the kind of trip you want.</h2></div><p className="max-w-md text-sm leading-6 text-slate-500">Start with a trek, a local experience or an active mountain break. Each category takes you directly to relevant journeys.</p></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{experiences.map(item => <Link key={item.title} href={`/tours?category=${encodeURIComponent(item.filter)}`} className="group relative isolate h-60 overflow-hidden rounded-xl bg-[#123d5b] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#e9781c] focus-visible:ring-offset-4"><img src={item.image} alt="" className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy" /><div className="absolute inset-0 bg-gradient-to-t from-[#082f4b]/95 via-[#082f4b]/20 to-transparent" /><div className="absolute bottom-0 p-5 text-white"><item.icon className="size-5 text-[#f39a48]" /><h3 className="display mt-3 text-2xl font-bold normal-case">{item.title}</h3><p className="mt-1 text-sm leading-5 text-white/72">{item.copy}</p></div></Link>)}</div></div></section>
    <section className="py-20 sm:py-24"><div className="container"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Curated by locals</p><h2 className="section-title mt-3 normal-case tracking-[-.03em]">Popular journeys</h2></div><Link href="/tours" className="focus-ring inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.1em] text-[#123d5b] hover:text-[#e17818]">All journeys <ArrowRight className="size-4" /></Link></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{tours.length ? tours.map(tour => <TourCard key={tour.id} tour={tour} />) : <div className="col-span-full rounded-2xl border border-dashed border-[#ccd9d7] p-10 text-center text-sm text-slate-500">Journeys are being prepared for your next escape.</div>}</div></div></section>
    <section className="bg-[#eef3ef] py-20"><div className="container grid gap-12 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div className="relative"><img src="/manus-storage/dharamshala-prayer-flags_26329188.jpg" alt="Prayer flags in Dharamshala" className="h-[360px] w-full rounded-xl object-cover shadow-[0_18px_40px_rgba(18,61,91,.13)]" loading="lazy" /><div className="absolute -bottom-5 left-5 max-w-[265px] border-l-4 border-[#e17818] bg-white px-5 py-4 shadow-lg"><p className="text-xs font-extrabold uppercase tracking-[.12em] text-[#e17818]">Route note · Dharamshala</p><p className="mt-1 text-sm font-bold leading-5 text-[#123d5b]">Season, pace and route context checked before we recommend a journey.</p></div></div><div><p className="eyebrow">Our local planning desk</p><h2 className="section-title mt-3 normal-case tracking-[-.03em]">A local team for the details that matter.</h2><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">We turn a mountain idea into a clear, well-supported plan. That means realistic timing, straightforward guidance and the right people around your trip.</p><div className="mt-8 grid gap-5 sm:grid-cols-2">{[[MapPinned, "Route knowledge", "Practical advice for the season and terrain."], [ShieldCheck, "Careful preparation", "Clear expectations before a journey begins."], [UsersRound, "Right-sized groups", "Trips designed for personal attention."], [HeartHandshake, "Useful communication", "Direct answers from a local planning team."]].map(([Icon, title, copy]) => <div key={String(title)} className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-white text-[#e17818]"><Icon className="size-5" /></span><span><strong className="text-sm text-[#123d5b]">{String(title)}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{String(copy)}</p></span></div>)}</div></div></div></section>
    <section className="bg-[#123d5b] py-20 text-white"><div className="container grid gap-8 lg:grid-cols-[.82fr_1.18fr] lg:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#f39a48]">Start with a simple enquiry</p><h2 className="display mt-4 max-w-lg text-4xl font-bold leading-[.95] sm:text-5xl">Tell us what you have in mind.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-white/72">Share a date, group size or a trip idea. Our Dharamshala planning team will review it and reply with a practical next step.</p></div>{enquirySent ? <div className="rounded-xl border border-white/15 bg-white/10 p-8 text-center"><CheckCircle2 className="mx-auto size-11 text-[#7ae4a5]" /><h3 className="display mt-4 text-3xl font-bold">Enquiry received</h3><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-white/72">Thank you. Your details are now with our Dharamshala planning desk.</p></div> : <form onSubmit={sendEnquiry} className="grid gap-3 rounded-xl border border-white/15 bg-white/8 p-4 sm:grid-cols-2 sm:p-5"><label className="sr-only" htmlFor="home-enquiry-name">Your name</label><input id="home-enquiry-name" name="name" required placeholder="Your name" className="focus-ring h-12 rounded-lg bg-white px-4 text-sm text-[#123d5b] outline-none placeholder:text-slate-400" /><label className="sr-only" htmlFor="home-enquiry-email">Email address</label><input id="home-enquiry-email" name="email" required type="email" placeholder="Email address" className="focus-ring h-12 rounded-lg bg-white px-4 text-sm text-[#123d5b] outline-none placeholder:text-slate-400" /><label className="sr-only" htmlFor="home-enquiry-phone">Phone or WhatsApp</label><input id="home-enquiry-phone" name="phone" placeholder="Phone / WhatsApp" className="focus-ring h-12 rounded-lg bg-white px-4 text-sm text-[#123d5b] outline-none placeholder:text-slate-400" /><label className="sr-only" htmlFor="home-enquiry-message">Trip details</label><input id="home-enquiry-message" name="message" required placeholder="Dates, group size or a trip idea" className="focus-ring h-12 rounded-lg bg-white px-4 text-sm text-[#123d5b] outline-none placeholder:text-slate-400" /><button disabled={enquiry.isPending} className="focus-ring h-12 rounded-lg bg-[#f39a48] px-5 text-xs font-extrabold uppercase tracking-[.1em] text-[#173d57] transition hover:bg-[#ffc17e] active:scale-[.97] disabled:opacity-60 sm:col-span-2">{enquiry.isPending ? "Sending enquiry…" : "Send enquiry"}</button>{enquiry.error && <p className="text-sm text-red-200 sm:col-span-2">{enquiry.error.message}</p>}</form>}</div></section>
    {reviews.length > 0 && <section className="bg-[#f8f5ef] py-20"><div className="container"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Traveller feedback</p><h2 className="section-title mt-3 normal-case tracking-[-.03em]">Real stories, simply shared.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">Only feedback verified and published by the Trip Himalaya team appears here.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{reviews.slice(0, 3).map(review => <article key={review.id} className="rounded-xl border border-[#eadfce] bg-white p-6 shadow-[0_12px_28px_rgba(18,61,91,.05)]"><div className="flex items-center gap-3"><div className="grid size-11 shrink-0 place-items-center overflow-hidden rounded-full bg-[#e6efeb] text-sm font-extrabold text-[#123d5b]">{review.reviewerImage ? <img src={review.reviewerImage} alt="" className="h-full w-full object-cover" /> : review.reviewerName.slice(0, 1).toUpperCase()}</div><div><p className="text-sm font-bold text-[#123d5b]">{review.reviewerName}</p><div className="mt-1 flex gap-0.5 text-[#e17818]" aria-label={`${review.rating} out of 5 stars`}>{Array.from({ length: 5 }, (_, index) => <Star key={index} className={`size-3 ${index < review.rating ? "fill-current" : "text-slate-200"}`} />)}</div></div></div><p className="mt-5 text-sm leading-7 text-slate-600">“{review.quote}”</p><p className="mt-5 border-t border-[#eee7dc] pt-4 text-xs text-slate-500">{[review.location, review.sourceLabel].filter(Boolean).join(" · ")}</p></article>)}</div></div></section>}
    <section className="bg-[#0d3653] py-16 text-white"><div className="container grid gap-8 lg:grid-cols-[1.25fr_.75fr] lg:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#f39a48]">Dharamshala travel notes</p><h2 className="display mt-3 text-3xl font-bold leading-none sm:text-4xl">Occasional practical notes for your next trip.</h2></div><form onSubmit={subscribe} className="rounded-xl bg-white/10 p-3"><label className="sr-only" htmlFor="newsletter-email">Email address</label><div className="flex gap-2"><input id="newsletter-email" type="email" value={email} onChange={e => setEmail(e.target.value)} required placeholder="Your email address" className="focus-ring h-12 min-w-0 flex-1 rounded-lg bg-white px-4 text-sm text-[#123d5b] outline-none" /><button disabled={newsletter.isPending} className="focus-ring rounded-lg bg-[#f39a48] px-4 text-xs font-extrabold uppercase tracking-[.08em] text-[#173d57] disabled:opacity-60">{newsletter.isPending ? "Saving" : "Subscribe"}</button></div>{newsletter.isSuccess && <p className="px-2 pt-2 text-xs text-white/75">You are on the list. Thank you.</p>}</form></div></section>
  </PublicLayout>;
}
