import PublicLayout from "@/components/PublicLayout";
import TourCard from "@/components/TourCard";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BadgeCheck, CalendarDays, CheckCircle2, Compass, HeartHandshake, Landmark, MapPinned, Mountain, Search, ShieldCheck, Sparkles, TentTree, UsersRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useLocation } from "wouter";

const experiences = [
  { title: "Trekking", filter: "Trekking", icon: Mountain, image: "/manus-storage/triund-hikers_7653a06a.jpg", copy: "Walk the ridges." },
  { title: "Culture", filter: "Experiences", icon: Landmark, image: "/manus-storage/dharamshala-prayer-flags_26329188.jpg", copy: "Travel with context." },
  { title: "Adventure", filter: "Adventure", icon: TentTree, image: "/manus-storage/triund-camp_ded436f5.jpg", copy: "Take the mountain further." },
  { title: "All journeys", filter: "All", icon: Compass, image: "/manus-storage/dharamshala-valley_971eee0a.jpg", copy: "See what calls you." },
];

export default function Home() {
  const { data: tours = [] } = trpc.tours.featured.useQuery();
  const { data: reviews = [] } = trpc.reviews.list.useQuery(undefined, { retry: false });
  const [, setLocation] = useLocation();
  const [query, setQuery] = useState("");
  const newsletter = trpc.newsletter.subscribe.useMutation();
  const enquiry = trpc.enquiries.create.useMutation();
  const [email, setEmail] = useState("");
  const [enquirySent, setEnquirySent] = useState(false);
  function search(event: FormEvent) { event.preventDefault(); if (query.trim()) setLocation(`/search?q=${encodeURIComponent(query.trim())}`); }
  function subscribe(event: FormEvent) { event.preventDefault(); newsletter.mutate({ email }, { onSuccess: () => setEmail("") }); }
  function sendEnquiry(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); enquiry.mutate({ name: String(form.get("name")), email: String(form.get("email")), phone: String(form.get("phone")) || undefined, subject: "Homepage trip enquiry", message: String(form.get("message")) }, { onSuccess: () => setEnquirySent(true) }); }
  return <PublicLayout>
    <section className="relative isolate min-h-[680px] overflow-hidden bg-[#0e3d5c] text-white lg:min-h-[730px]">
      <img src="/manus-storage/dharamshala-valley_971eee0a.jpg" alt="Dhauladhar views above Dharamshala" className="absolute inset-0 h-full w-full object-cover" fetchPriority="high" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,39,61,.91)_0%,rgba(7,39,61,.7)_42%,rgba(7,39,61,.14)_100%)]" /><div className="absolute inset-x-0 bottom-0 h-44 bg-gradient-to-t from-[#0b3553] to-transparent" />
      <div className="container relative flex min-h-[680px] flex-col justify-center py-24 lg:min-h-[730px]">
        <div className="max-w-3xl"><div className="rise inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-[.68rem] font-extrabold uppercase tracking-[.14em] text-white/85"><span className="size-1.5 rounded-full bg-[#f39a48]" /> Local journeys · Dharamshala</div><h1 className="rise-2 mt-6 max-w-2xl font-display text-[clamp(3.5rem,9vw,7rem)] font-bold uppercase leading-[.79] tracking-[-.055em]">Discover Himachal.<br /><span className="text-[#f39a48]">Feel the Himalayas.</span></h1><p className="rise-3 mt-7 max-w-xl text-base leading-7 text-white/82 sm:text-lg">A better-paced way to trek, pause and explore. Local insight from the best tour agency in Dharamshala, India.</p></div>
        <div className="rise-3 mt-9 flex flex-wrap gap-3"><Link href="/tours" className="focus-ring inline-flex h-12 items-center gap-2 rounded-xl bg-[#ed7b1c] px-5 text-xs font-extrabold uppercase tracking-[.1em] text-white shadow-xl shadow-black/10 transition hover:bg-[#db6a0e] active:scale-[.97]">Explore journeys <ArrowRight className="size-4" /></Link><Link href="/contact" className="focus-ring inline-flex h-12 items-center gap-2 rounded-xl border border-white/45 bg-white/10 px-5 text-xs font-extrabold uppercase tracking-[.1em] text-white backdrop-blur transition hover:bg-white/20 active:scale-[.97]"><CalendarDays className="size-4" /> Plan your trip</Link></div>
        <form onSubmit={search} className="rise-3 mt-12 grid max-w-4xl gap-2 rounded-[1.2rem] border border-white/20 bg-white/12 p-3 backdrop-blur-md sm:grid-cols-[1fr_auto]" role="search"><label className="sr-only" htmlFor="hero-search">Search trips</label><div className="flex items-center gap-3 px-3"><Search className="size-5 shrink-0 text-[#f5a653]" /><input id="hero-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Where do you want to go? Try Triund or Bir…" className="h-11 min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-white/54" /></div><button className="focus-ring h-11 rounded-xl bg-white px-6 text-xs font-extrabold uppercase tracking-[.1em] text-[#123d5b] transition hover:bg-[#f7f1e8] active:scale-[.97]">Find a journey</button></form>
      </div>
      <div className="relative border-t border-white/14 bg-[#0b3553]/90 backdrop-blur"><div className="container grid divide-y divide-white/12 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4">{[[UsersRound, "Local people", "Guides who know the routes."], [BadgeCheck, "Clear pricing", "Thoughtful, upfront planning."], [ShieldCheck, "Mountain-aware", "Safety matters at every step."], [HeartHandshake, "Human support", "Helpful before and during travel."]].map(([Icon, title, copy]) => <div key={String(title)} className="flex items-center gap-3 px-3 py-4 sm:px-5"><Icon className="size-6 shrink-0 text-[#f39a48]" /><span><strong className="block text-xs font-extrabold uppercase tracking-[.06em]">{String(title)}</strong><span className="mt-1 block text-xs text-white/63">{String(copy)}</span></span></div>)}</div></div>
    </section>
    <section className="mountain-grid py-20 sm:py-24"><div className="container"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Choose your own way</p><h2 className="section-title mt-3">One range.<br />Many ways in.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">Take the trail, follow a local story, or leave room for a slow mountain morning.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{experiences.map(item => <Link key={item.title} href={`/tours?category=${encodeURIComponent(item.filter)}`} className="group relative isolate h-64 overflow-hidden rounded-[1.35rem] bg-[#123d5b] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#e9781c] focus-visible:ring-offset-4"><img src={item.image} alt="" className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-110" loading="lazy" /><div className="absolute inset-0 bg-gradient-to-t from-[#082f4b]/95 via-[#082f4b]/18 to-transparent" /><div className="absolute bottom-0 p-5 text-white"><item.icon className="size-5 text-[#f39a48]" /><h3 className="display mt-4 text-3xl font-bold">{item.title}</h3><p className="mt-1 text-sm text-white/70">{item.copy}</p></div></Link>)}</div></div></section>
    <section className="py-20 sm:py-24"><div className="container"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Curated by locals</p><h2 className="section-title mt-3">Popular journeys</h2></div><Link href="/tours" className="focus-ring inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.1em] text-[#123d5b] hover:text-[#e17818]">All journeys <ArrowRight className="size-4" /></Link></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{tours.length ? tours.map(tour => <TourCard key={tour.id} tour={tour} />) : <div className="col-span-full rounded-2xl border border-dashed border-[#ccd9d7] p-10 text-center text-sm text-slate-500">Journeys are being prepared for your next escape.</div>}</div></div></section>
    <section className="bg-[#eaf1ed] py-20"><div className="container grid gap-12 lg:grid-cols-[.92fr_1.08fr] lg:items-center"><div className="relative"><img src="/manus-storage/dharamshala-prayer-flags_26329188.jpg" alt="Dharamshala hillside seen through prayer flags" className="h-[380px] w-full rounded-[1.6rem] object-cover shadow-2xl" loading="lazy" /><div className="absolute -bottom-6 -right-3 max-w-[220px] rounded-2xl bg-[#f39a48] p-5 text-[#173d57] shadow-xl sm:right-6"><Sparkles className="size-5" /><p className="display mt-3 text-2xl font-bold leading-none">Less rushing.<br />More feeling.</p></div></div><div><p className="eyebrow">Why Trip Himalaya</p><h2 className="section-title mt-3">Travel can be<br />well held.</h2><p className="mt-6 max-w-xl text-base leading-7 text-slate-600">We build simple plans with enough breathing room. Your guide, pace and choices should make sense for the mountains, not for a template.</p><div className="mt-8 grid gap-5 sm:grid-cols-2">{[[MapPinned, "Local routes", "Ground knowledge from the people who live here."], [ShieldCheck, "Good preparation", "Clear advice before you say yes to a trail."], [UsersRound, "Small by design", "More attention for each traveller."], [HeartHandshake, "Direct support", "Real people when you need an answer."]].map(([Icon, title, copy]) => <div key={String(title)} className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white text-[#e17818]"><Icon className="size-5" /></span><span><strong className="text-sm text-[#123d5b]">{String(title)}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{String(copy)}</p></span></div>)}</div></div></div></section>
    <section className="relative overflow-hidden bg-[#0d3653] py-20 text-white"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_12%_10%,#e9781c_0,transparent_28%),radial-gradient(circle_at_88%_84%,#59a1a9_0,transparent_26%)]" /><div className="container relative grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow !text-[#f39a48]">Plan with a local team</p><h2 className="display mt-3 max-w-lg text-4xl font-bold leading-none sm:text-5xl">Tell us how you want the mountains to feel.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-white/72">Share your dates, group and wish list. We will confirm your enquiry and reply with a useful next step.</p></div>{enquirySent ? <div className="rounded-[1.35rem] border border-white/15 bg-white/10 p-8 text-center backdrop-blur"><CheckCircle2 className="mx-auto size-11 text-[#7ae4a5]" /><h3 className="display mt-4 text-3xl font-bold">Enquiry received.</h3><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-white/72">Thank you. Your details are now with our Dharamshala planning desk.</p></div> : <form onSubmit={sendEnquiry} className="grid gap-3 rounded-[1.35rem] border border-white/15 bg-white/10 p-4 backdrop-blur sm:grid-cols-2 sm:p-5"><label className="sr-only" htmlFor="home-enquiry-name">Your name</label><input id="home-enquiry-name" name="name" required placeholder="Your name" className="focus-ring h-12 rounded-xl bg-white px-4 text-sm text-[#123d5b] outline-none placeholder:text-slate-400" /><label className="sr-only" htmlFor="home-enquiry-email">Email address</label><input id="home-enquiry-email" name="email" required type="email" placeholder="Email address" className="focus-ring h-12 rounded-xl bg-white px-4 text-sm text-[#123d5b] outline-none placeholder:text-slate-400" /><label className="sr-only" htmlFor="home-enquiry-phone">Phone or WhatsApp</label><input id="home-enquiry-phone" name="phone" placeholder="Phone / WhatsApp" className="focus-ring h-12 rounded-xl bg-white px-4 text-sm text-[#123d5b] outline-none placeholder:text-slate-400" /><label className="sr-only" htmlFor="home-enquiry-message">Trip details</label><input id="home-enquiry-message" name="message" required placeholder="Dates, group size or a trip idea" className="focus-ring h-12 rounded-xl bg-white px-4 text-sm text-[#123d5b] outline-none placeholder:text-slate-400" /><button disabled={enquiry.isPending} className="focus-ring h-12 rounded-xl bg-[#f39a48] px-5 text-xs font-extrabold uppercase tracking-[.1em] text-[#173d57] transition hover:bg-[#ffc17e] active:scale-[.97] disabled:opacity-60 sm:col-span-2">{enquiry.isPending ? "Sending enquiry…" : "Send enquiry"}</button>{enquiry.error && <p className="text-sm text-red-200 sm:col-span-2">{enquiry.error.message}</p>}</form>}</div></section>
    {reviews.length > 0 && <section className="bg-[#f8f5ef] py-20"><div className="container"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Shared by travellers</p><h2 className="section-title mt-3">Stories from the trail.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">Only feedback verified and published by the Trip Himalaya team appears here.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{reviews.slice(0, 3).map(review => <article key={review.id} className="rounded-2xl border border-[#eadfce] bg-white p-6 shadow-[0_12px_28px_rgba(18,61,91,.05)]"><p className="text-sm leading-7 text-slate-600">“{review.quote}”</p><div className="mt-6 border-t border-[#eee7dc] pt-4"><p className="text-sm font-bold text-[#123d5b]">{review.reviewerName}</p><p className="mt-1 text-xs text-slate-500">{[review.location, review.sourceLabel].filter(Boolean).join(" · ")}</p></div></article>)}</div></div></section>}
    <section className="relative overflow-hidden bg-[#123d5b] py-16 text-white"><div className="absolute inset-0 opacity-25 [background-image:radial-gradient(circle_at_15%_20%,#ef8928_0,transparent_35%),radial-gradient(circle_at_85%_80%,#5cb1be_0,transparent_30%)]" /><div className="container relative grid gap-8 lg:grid-cols-[1.25fr_.75fr] lg:items-center"><div><p className="eyebrow !text-[#f39a48]">Fresh mountain notes</p><h2 className="display mt-3 text-4xl font-bold leading-none sm:text-5xl">Make your next trip feel more like yours.</h2></div><form onSubmit={subscribe} className="rounded-2xl bg-white/10 p-3 backdrop-blur"><label className="sr-only" htmlFor="newsletter-email">Email address</label><div className="flex gap-2"><input id="newsletter-email" type="email" value={email} onChange={e => setEmail(e.target.value)} required placeholder="Your email address" className="focus-ring h-12 min-w-0 flex-1 rounded-xl bg-white px-4 text-sm text-[#123d5b] outline-none" /><button disabled={newsletter.isPending} className="focus-ring rounded-xl bg-[#f39a48] px-4 text-xs font-extrabold uppercase tracking-[.08em] text-[#173d57] disabled:opacity-60">{newsletter.isPending ? "Saving" : "Keep me posted"}</button></div>{newsletter.isSuccess && <p className="px-2 pt-2 text-xs text-white/75">You are on the list. Thank you.</p>}</form></div></section>
  </PublicLayout>;
}
