import PublicLayout from "@/components/PublicLayout";
import { ArrowRight, Check, Compass, HeartHandshake, Landmark, MapPinned, Mountain, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";

const principles = [[Compass, "Practical local advice", "Routes and pacing that work for your dates and group."], [ShieldCheck, "Clear preparation", "Straight answers on weather, packing and the plan."], [HeartHandshake, "Direct support", "A local team you can speak with before your trip."]];
const services = [[Mountain, "Trek planning", "Guides, stays and practical support for the right pace."], [MapPinned, "Dharamshala days", "Local plans around McLeod Ganj, Kangra and nearby valleys."], [UsersRound, "Private trips", "Thoughtful arrangements for friends, families and small groups."]];

export default function PublicPage({ kind }: { kind: "about" | "experiences" }) { return <PublicLayout>{kind === "about" ? <AboutPage /> : <ExperiencesPage />}</PublicLayout>; }

function PageHero({ eyebrow, title, copy }: { eyebrow: string; title: React.ReactNode; copy: string }) { return <section className="relative overflow-hidden bg-[#123d5b] py-16 text-white sm:py-20"><div className="absolute inset-0 mountain-grid opacity-20" /><div className="container relative"><p className="eyebrow !text-[#f39a48]">{eyebrow}</p><h1 className="display mt-4 max-w-3xl text-[clamp(3.25rem,8vw,6.25rem)] font-bold leading-[.84]">{title}</h1><p className="mt-6 max-w-xl text-base leading-7 text-white/75">{copy}</p><Link href="/contact" className="focus-ring mt-7 inline-flex h-11 items-center gap-2 rounded-lg border border-white/30 bg-white/10 px-4 text-xs font-extrabold uppercase tracking-[.09em] text-white backdrop-blur-sm hover:bg-white/18">Plan your trip <ArrowRight className="size-4" /></Link></div></section>; }

function AboutPage() { return <>
  <PageHero eyebrow="About Trip Himalaya" title={<>Dharamshala travel<br />planned with <span className="text-[#f39a48]">local care.</span></>} copy="Clear trips, useful local advice and real support from a Dharamshala-based team." />
  <section className="container grid gap-10 py-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-20"><div><p className="eyebrow">Who we are</p><h2 className="section-title mt-3 normal-case tracking-[-.03em]">A practical team, close to the routes.</h2><p className="mt-6 max-w-xl text-base leading-7 text-slate-600">We coordinate treks, stays and local days from Dharamshala. You get a realistic route, the right pace and clear support before you arrive.</p><Link href="/contact" className="focus-ring mt-7 inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.1em] text-[#123d5b] hover:text-[#e17818]">Talk to the local team <ArrowRight className="size-4" /></Link></div><img src="/manus-storage/triund-hikers_7653a06a.jpg" alt="Hikers on a Himachal trail" className="h-[360px] w-full rounded-[1.5rem] object-cover shadow-[0_18px_38px_rgba(18,61,91,.12)]" loading="lazy" /></section>
  <section className="bg-[#eef4f2] py-16 lg:py-20"><div className="container grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><div className="rounded-[1.4rem] bg-[#123d5b] p-7 text-white"><p className="text-xs font-extrabold uppercase tracking-[.15em] text-[#f39a48]">Our mission</p><h2 className="display mt-4 text-4xl font-bold leading-[.9]">Make mountain travel feel informed, not complicated.</h2><p className="mt-5 text-sm leading-6 text-white/72">Every journey should start with a clear plan, the right support and a respectful approach to the place and people you are visiting.</p></div><div className="grid gap-4 sm:grid-cols-3">{principles.map(([Icon, title, copy]) => <article key={String(title)} className="rounded-[1.4rem] bg-white p-6 shadow-[0_10px_24px_rgba(18,61,91,.05)]"><span className="grid size-10 place-items-center rounded-xl bg-[#f8f0e6] text-[#e17818]"><Icon className="size-5" /></span><h3 className="mt-5 text-base font-bold text-[#123d5b]">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{String(copy)}</p></article>)}</div></div></section>
  <section className="container py-16 lg:py-20"><div className="max-w-2xl"><p className="eyebrow">What we help with</p><h2 className="section-title mt-3 normal-case tracking-[-.03em]">Simple support for your trip.</h2><p className="mt-5 text-base leading-7 text-slate-600">Tell us your dates and what you enjoy. We will help with the practical details.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{services.map(([Icon, title, copy]) => <article key={String(title)} className="rounded-[1.35rem] border border-[#dfe8e8] bg-white p-6 shadow-[0_10px_24px_rgba(18,61,91,.05)]"><span className="grid size-11 place-items-center rounded-xl bg-[#eef4f2] text-[#e17818]"><Icon className="size-5" /></span><h3 className="mt-6 text-lg font-bold text-[#123d5b]">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{String(copy)}</p></article>)}</div></section>
  <section className="border-y border-[#dfe8e8] bg-[#fbfaf6] py-16"><div className="container grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow">How we work</p><h2 className="section-title mt-3 normal-case tracking-[-.03em]">The values behind every plan.</h2></div><div className="grid gap-3 sm:grid-cols-2">{["Keep the route realistic.", "Respect the mountain and local communities.", "Communicate clearly before every trip.", "Recommend what fits, not what fills a schedule."].map(value => <p key={value} className="flex gap-3 rounded-xl border border-[#dfe8e8] bg-white p-4 text-sm font-semibold text-[#214861]"><Check className="mt-0.5 size-4 shrink-0 text-[#e17818]" />{value}</p>)}</div></div></section>
  <section className="bg-[#123d5b] py-16 text-white"><div className="container flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#f39a48]">Plan with Trip Himalaya</p><h2 className="display mt-2 text-4xl font-bold">Start with a simple conversation.</h2></div><Link href="/contact" className="focus-ring inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[#e9781c] px-5 text-xs font-extrabold uppercase tracking-[.1em] text-white hover:bg-[#d86b12]">Plan your trip <ArrowRight className="size-4" /></Link></div></section>
</>; }

function ExperiencesPage() { const experiences = [[Landmark, "A day around McLeod Ganj", "Culture, food and a clear feel for upper Dharamshala."], [UsersRound, "A private family escape", "Flexible timing and smaller distances for more shared time."], [Mountain, "A trail with a guide", "Walk a route that matches your confidence and time."], [Compass, "A slow Kangra Valley day", "Views, local stops and space to take it in."], [HeartHandshake, "A celebration in the hills", "A useful plan for a birthday, reunion or meaningful pause."], [Check, "A made-to-fit week", "Join treks, local stays and free days in one simple plan."]]; return <><PageHero eyebrow="Beyond a checklist" title={<>Choose an<br /><span className="text-[#f39a48]">experience</span>, not just a stop.</>} copy="Private mountain moments, cultural context and fresh air—put together around the way you actually want to travel." /><section className="container py-16 sm:py-22"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{experiences.map(([Icon, title, copy]) => <div key={String(title)} className="rounded-[1.35rem] border border-[#dfe8e8] bg-white p-6 shadow-[0_10px_24px_rgba(18,61,91,.05)]"><span className="grid size-11 place-items-center rounded-xl bg-[#eef4f2] text-[#e17818]"><Icon className="size-5" /></span><h2 className="display mt-6 text-3xl font-bold text-[#123d5b]">{String(title)}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{String(copy)}</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.1em] text-[#123d5b] hover:text-[#e17818]">Plan this <ArrowRight className="size-4" /></Link></div>)}</div></section></>; }
