import PublicLayout from "@/components/PublicLayout";
import { formatPublishedJourneyCount } from "@/lib/companyFacts";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Check, Compass, HeartHandshake, Landmark, MapPinned, Mountain, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";

const principles = [[Compass, "Practical local advice", "Routes and pacing that work for your dates and group."], [ShieldCheck, "Clear preparation", "Straight answers on weather, packing and the plan."], [HeartHandshake, "Direct support", "A local team you can speak with before your trip."]];
const services = [[Mountain, "Trek planning", "Guides, stays and practical support for the right pace."], [MapPinned, "Dharamshala days", "Local plans around McLeod Ganj, Kangra and nearby valleys."], [UsersRound, "Private trips", "Thoughtful arrangements for friends, families and small groups."]];

export default function PublicPage({ kind }: { kind: "about" | "experiences" }) {
  return <PublicLayout>{kind === "about" ? <AboutPage /> : <ExperiencesPage />}</PublicLayout>;
}

function PageHero({ eyebrow, title, copy }: { eyebrow: string; title: React.ReactNode; copy: string }) {
  return <section className="relative overflow-hidden border-b border-[#254f68] bg-[#123d5b] py-20 text-white sm:py-24"><div className="absolute inset-0 mountain-grid opacity-15" /><div className="container relative max-w-[1280px]"><p className="eyebrow !text-[#f39a48]">{eyebrow}</p><h1 className="font-display mt-4 max-w-3xl text-[clamp(3rem,6.4vw,5.4rem)] font-bold leading-[.93] tracking-[-.035em]">{title}</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/75">{copy}</p><Link href="/contact" className="focus-ring mt-7 inline-flex h-11 items-center gap-2 border border-white/30 bg-white/8 px-4 text-sm font-bold text-white transition hover:bg-white/16">Plan your trip <ArrowRight className="size-4" /></Link></div></section>;
}

function AboutPage() {
  const { data: publishedTours } = trpc.tours.list.useQuery();
  const companyCards = [
    [MapPinned, "Our base", "Dharamshala, Himachal", "Local planning from the Kangra Valley."],
    [Mountain, "Current journeys", publishedTours ? formatPublishedJourneyCount(publishedTours.length) : "Current journeys", "Treks, stays and flexible mountain days."],
    [Compass, "How we plan", "Route-led travel", "Plans shaped around season, time and pace."],
    [HeartHandshake, "How to reach us", "Direct planning support", "Start with a question and get a clear next step."],
  ] as const;

  return <>
    <PageHero eyebrow="About Trip Himalaya" title={<>A Dharamshala team for clear, thoughtful travel.</>} copy="Treks, local stays and private journeys planned with useful local knowledge." />
    <section className="container grid gap-10 py-16 lg:grid-cols-[1.03fr_.97fr] lg:items-center lg:py-20"><div><p className="eyebrow">The agency</p><h2 className="section-title mt-3 max-w-xl">A clear local agency for Himachal travel.</h2><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">Trip Himalaya plans treks, local stays and private trips from Dharamshala. We make the route, timing and next step easy to understand before you travel.</p><p className="mt-4 max-w-xl text-base leading-7 text-slate-600">Choose a day out, a guided trek or a short mountain break. We begin with your dates and group, then build a plan that fits.</p><Link href="/contact" className="focus-ring mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#123d5b] hover:text-[#e17818]">Talk to the local team <ArrowRight className="size-4" /></Link></div><img src="/manus-storage/triund-hikers_7653a06a.jpg" alt="Hikers on a Himachal trail" className="h-[350px] w-full object-cover shadow-[0_16px_34px_rgba(18,61,91,.1)]" loading="lazy" /></section>
    <section className="border-y border-[#dfe8e8] bg-[#fbfaf6] py-12 sm:py-14"><div className="container"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="eyebrow">Trip Himalaya at a glance</p><h2 className="section-title mt-3">What we do, clearly.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-600">Simple information for travellers who want a better mountain plan.</p></div><div className="mt-8 grid overflow-hidden border border-[#d7e1dc] bg-[#d7e1dc] sm:grid-cols-2 lg:grid-cols-4">{companyCards.map(([Icon, eyebrow, title, copy]) => <article key={title} className="min-h-52 bg-white p-5 sm:p-6"><span aria-hidden="true" className="grid size-10 place-items-center rounded-full bg-[#edf3ef] text-[#e17818]"><Icon className="size-5" /></span><p className="mt-7 text-[11px] font-extrabold uppercase tracking-[.12em] text-[#b55f18]">{eyebrow}</p><h3 className="mt-2 font-display text-2xl font-bold leading-tight text-[#123d5b]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>
    <section className="border-y border-[#dfe8e8] bg-[#f4f6f3] py-16 lg:py-20"><div className="container grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Our mission</p><h2 className="section-title mt-3">Keep mountain travel informed, not complicated.</h2><p className="mt-5 text-base leading-7 text-slate-600">Every trip should begin with a plan you understand and support you can rely on.</p></div><div className="divide-y divide-[#d3dfda] border-y border-[#d3dfda]">{principles.map(([Icon, title, copy]) => <div key={String(title)} className="flex gap-4 py-5"><Icon className="mt-0.5 size-5 shrink-0 text-[#e17818]" /><div><h3 className="text-base font-bold text-[#123d5b]">{String(title)}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{String(copy)}</p></div></div>)}</div></div></section>
    <section className="container py-16 lg:py-20"><div className="max-w-2xl"><p className="eyebrow">What we help with</p><h2 className="section-title mt-3">Useful support, from first question to final plan.</h2></div><div className="mt-8 divide-y divide-[#dfe8e8] border-y border-[#dfe8e8]">{services.map(([Icon, title, copy], index) => <div key={String(title)} className="grid gap-3 py-5 sm:grid-cols-[3rem_14rem_1fr] sm:items-start"><span className="font-display text-3xl font-bold text-[#e17818]">0{index + 1}</span><div className="flex gap-3"><Icon className="mt-0.5 size-5 shrink-0 text-[#123d5b]" /><h3 className="text-base font-bold text-[#123d5b]">{String(title)}</h3></div><p className="text-sm leading-6 text-slate-600">{String(copy)}</p></div>)}</div></section>
    <section className="border-t border-[#dfe8e8] bg-[#fbfaf6] py-14"><div className="container grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow">How we work</p><h2 className="section-title mt-3">Good plans stay simple.</h2></div><ul className="grid gap-3 sm:grid-cols-2">{["Keep the route realistic.", "Respect the mountain and local communities.", "Communicate clearly before every trip.", "Recommend what fits, not what fills a schedule."].map(value => <li key={value} className="flex gap-3 text-sm font-semibold leading-6 text-[#214861]"><Check className="mt-1 size-4 shrink-0 text-[#e17818]" />{value}</li>)}</ul></div></section>
    <section className="bg-[#123d5b] py-14 text-white"><div className="container flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#f39a48]">Plan with Trip Himalaya</p><h2 className="font-display mt-2 text-4xl font-bold">Start with a simple conversation.</h2></div><Link href="/contact" className="focus-ring inline-flex h-12 items-center justify-center gap-2 bg-[#e9781c] px-5 text-sm font-bold text-white hover:bg-[#d86b12]">Plan your trip <ArrowRight className="size-4" /></Link></div></section>
  </>;
}

function ExperiencesPage() {
  const experiences = [[Landmark, "A day around McLeod Ganj", "Culture, food and a clear feel for upper Dharamshala."], [UsersRound, "A private family escape", "Flexible timing and smaller distances for more shared time."], [Mountain, "A trail with a guide", "Walk a route that matches your confidence and time."], [Compass, "A slow Kangra Valley day", "Views, local stops and space to take it in."], [HeartHandshake, "A celebration in the hills", "A useful plan for a birthday, reunion or meaningful pause."], [Check, "A made-to-fit week", "Join treks, local stays and free days in one simple plan."]];
  return <><PageHero eyebrow="Beyond a checklist" title={<>Experiences built around the way you want to travel.</>} copy="Private mountain moments, local context and fresh air—put together around your time in Himachal." /><section className="container py-16 sm:py-20"><div className="max-w-xl"><p className="eyebrow">Make it your own</p><h2 className="section-title mt-3">Start with an idea.</h2></div><div className="mt-8 divide-y divide-[#dfe8e8] border-y border-[#dfe8e8]">{experiences.map(([Icon, title, copy], index) => <article key={String(title)} className="grid gap-3 py-5 sm:grid-cols-[3rem_15rem_1fr_auto] sm:items-center"><span className="font-display text-3xl font-bold text-[#e17818]">0{index + 1}</span><div className="flex gap-3"><Icon className="mt-0.5 size-5 shrink-0 text-[#123d5b]" /><h2 className="text-base font-bold text-[#123d5b]">{String(title)}</h2></div><p className="text-sm leading-6 text-slate-600">{String(copy)}</p><Link href="/contact" className="focus-ring inline-flex items-center gap-2 text-sm font-bold text-[#123d5b] hover:text-[#e17818]">Plan this <ArrowRight className="size-4" /></Link></article>)}</div></section></>;
}
