import PublicLayout from "@/components/PublicLayout";
import Seo from "@/components/Seo";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ChevronRight, ExternalLink, MessageCircle, Phone, Quote, ShieldCheck, Star } from "lucide-react";
import { Link } from "wouter";

function Stars({ rating }: { rating: number }) {
  return <div className="flex gap-1" aria-label={`${rating} out of 5 stars`}>{Array.from({ length: 5 }).map((_, index) => <Star key={index} className={index < Math.round(rating) ? "size-4 fill-star text-star" : "size-4 text-slate-200"} aria-hidden="true" />)}</div>;
}

function formattedDate(value: Date | string) {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "Published guest feedback" : new Intl.DateTimeFormat("en-IN", { month: "short", year: "numeric" }).format(date);
}

export default function Reviews() {
  const { data: reviews = [] } = trpc.reviews.list.useQuery(undefined, { retry: false });
  const { data: agency } = trpc.agency.get.useQuery(undefined, { staleTime: 60_000 });
  const average = reviews.length ? reviews.reduce((total, item) => total + item.rating, 0) / reviews.length : 0;
  const googleReviewsUrl = agency?.reviewCtaEnabled === false ? "" : agency?.googleMapsUrl?.trim();
  const reviewSectionTitle = agency?.reviewSectionTitle || "TRAVELLED. REMEMBERED. SHARED.";
  const reviewSectionIntro = agency?.reviewSectionIntro || "Stories published from genuine Trip Himalaya guests, after the administration team has reviewed them.";
  const reviewCtaLabel = agency?.reviewCtaLabel || "VIEW GOOGLE REVIEWS";
  const phoneHref = `tel:${(agency?.phone || "+918219628359").replace(/[^+0-9]/g, "")}`;
  const whatsappNumber = (agency?.whatsapp || "918219628359").replace(/\D/g, "");

  return <PublicLayout>
    <Seo title="Traveller Feedback | Trip Himalaya Dharamshala" description="Read administrator-published Trip Himalaya traveller feedback and use the genuine external review destination when it is configured by the agency." structuredData={{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${window.location.origin}/` }, { "@type": "ListItem", position: 2, name: "Traveller Feedback", item: `${window.location.origin}/reviews` }] }} />
    <section className="relative overflow-hidden bg-primary-deep py-16 text-primary-foreground sm:py-20">
      <div className="absolute inset-0 opacity-40" style={{ backgroundImage: "radial-gradient(circle at 80% 20%, rgba(225,120,24,.36), transparent 26rem), linear-gradient(110deg, rgba(255,255,255,.06) 1px, transparent 1px)", backgroundSize: "auto, 28px 28px" }} aria-hidden="true" />
      <div className="relative mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[1.15fr_.85fr] lg:items-end">
        <div><p className="inline-flex items-center gap-2 rounded-full border border-primary-foreground/20 bg-primary-foreground/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[.18em]"><CheckCircle2 className="size-3.5 text-accent" /> Traveller feedback</p><h1 className="mt-5 max-w-3xl font-display text-4xl font-bold leading-[.95] tracking-wide sm:text-6xl">{reviewSectionTitle}</h1><p className="mt-5 max-w-xl text-sm leading-7 text-primary-foreground/80 sm:text-base">{reviewSectionIntro}</p></div>
        <div className="rounded-2xl border border-primary-foreground/15 bg-primary-foreground/10 p-6 backdrop-blur-sm"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-accent">Published guest feedback</p>{reviews.length ? <><div className="mt-3 flex items-end gap-3"><span className="font-display text-6xl font-bold leading-none text-primary-foreground">{average.toFixed(1)}</span><div className="pb-1"><Stars rating={average} /><p className="mt-2 text-xs leading-5 text-primary-foreground/70">Average from {reviews.length} published guest {reviews.length === 1 ? "review" : "reviews"}.</p></div></div></> : <p className="mt-3 text-sm leading-6 text-primary-foreground/80">Guest stories will appear here after the Trip Himalaya team has received and approved them.</p>}<p className="mt-5 border-t border-primary-foreground/15 pt-4 text-[11px] leading-5 text-primary-foreground/60">This page shows only feedback entered and published by Trip Himalaya administration. It does not claim Google verification or endorsement.</p></div>
      </div>
    </section>

    <section className="bg-[#f8fbfa] py-14 sm:py-20"><div className="mx-auto max-w-7xl px-5"><div className="mb-9 flex flex-col justify-between gap-4 border-b border-[#dce8e3] pb-6 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-accent">Guest stories</p><h2 className="mt-2 font-display text-3xl font-bold tracking-wide text-primary sm:text-4xl">REAL TRAVELLERS. REAL EXPERIENCES.</h2></div>{googleReviewsUrl ? <a href={googleReviewsUrl} target="_blank" rel="noreferrer" className="focus-ring inline-flex w-fit items-center gap-2 text-sm font-bold text-primary underline decoration-accent decoration-2 underline-offset-4">{reviewCtaLabel} <ExternalLink className="size-4" /></a> : null}</div>{reviews.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{reviews.map(item => <article key={item.id} className="group flex min-h-72 flex-col rounded-2xl border border-[#dce8e3] bg-white p-6 shadow-[0_14px_38px_rgba(18,61,91,.06)] transition-transform duration-200 hover:-translate-y-1"><div className="flex items-start justify-between gap-4"><Stars rating={item.rating} /><Quote className="size-7 text-accent/70" aria-hidden="true" /></div><p className="mt-6 flex-1 text-[15px] leading-7 text-slate-600">“{item.quote}”</p><div className="mt-7 flex items-center gap-3 border-t border-[#edf2f0] pt-5"><span className="grid size-10 shrink-0 place-items-center overflow-hidden rounded-full bg-[#eef4f2] text-sm font-extrabold text-primary">{item.reviewerImage ? <img src={item.reviewerImage} alt="" className="h-full w-full object-cover" loading="lazy" /> : item.reviewerName.charAt(0)}</span><div className="min-w-0"><p className="truncate text-sm font-bold text-primary">{item.reviewerName}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{item.location || item.sourceLabel || "Published guest feedback"} · {formattedDate(item.createdAt)}</p></div></div></article>)}</div> : <div className="rounded-2xl border border-dashed border-[#c7d8d2] bg-white px-6 py-14 text-center"><ShieldCheck className="mx-auto size-9 text-accent" /><h2 className="mt-4 font-display text-2xl font-bold tracking-wide text-primary">GUEST STORIES ARE ON THE WAY</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Trip Himalaya will publish genuine guest feedback here after it has been received and reviewed. In the meantime, contact the team directly to plan your journey.</p><Link href="/contact" className="focus-ring mt-6 inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-3 text-xs font-bold tracking-wide text-primary-foreground transition-transform hover:scale-[1.02]">CONTACT TRIP HIMALAYA <ChevronRight className="size-4" /></Link></div>}</div></section>

    <section className="bg-background py-12"><div className="mx-auto grid max-w-7xl gap-5 px-5 md:grid-cols-3"><a href={phoneHref} className="focus-ring group rounded-2xl border border-[#dce8e3] bg-white p-5 shadow-[0_10px_24px_rgba(18,61,91,.05)] transition-transform hover:-translate-y-0.5"><Phone className="size-5 text-accent" /><h2 className="mt-4 font-display text-xl font-bold tracking-wide text-primary">CALL NOW</h2><p className="mt-1 text-sm text-muted-foreground">Speak with Trip Himalaya about your dates and route.</p></a><a href={`https://wa.me/${whatsappNumber}?text=${encodeURIComponent("Hello, I would like to know more about your Dharamshala tour packages.")}`} target="_blank" rel="noreferrer" className="focus-ring group rounded-2xl border border-[#dce8e3] bg-white p-5 shadow-[0_10px_24px_rgba(18,61,91,.05)] transition-transform hover:-translate-y-0.5"><MessageCircle className="size-5 text-[#25D366]" /><h2 className="mt-4 font-display text-xl font-bold tracking-wide text-primary">WHATSAPP</h2><p className="mt-1 text-sm text-muted-foreground">Message the team for a quick, practical response.</p></a><Link href="/contact" className="focus-ring group rounded-2xl bg-primary p-5 text-primary-foreground shadow-[0_10px_24px_rgba(18,61,91,.12)] transition-transform hover:-translate-y-0.5"><ChevronRight className="size-5 text-accent" /><h2 className="mt-4 font-display text-xl font-bold tracking-wide">GET A QUOTE</h2><p className="mt-1 text-sm text-primary-foreground/70">Share your travel plans and receive tailored guidance.</p></Link></div></section>
  </PublicLayout>;
}
