import PublicLayout from "@/components/PublicLayout";
import TourCard from "@/components/TourCard";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Search } from "lucide-react";
import { FormEvent, useState } from "react";
import { useSearch } from "wouter";

export default function SearchPage() { const search = useSearch(); const initial = new URLSearchParams(search).get("q") || ""; const [query, setQuery] = useState(initial); const [submitted, setSubmitted] = useState(initial); const { data, isFetching } = trpc.tours.search.useQuery({ query: submitted || "__" }, { enabled: submitted.trim().length >= 2 }); function submit(e: FormEvent) { e.preventDefault(); setSubmitted(query.trim()); } return <PublicLayout><section className="container py-14 sm:py-20"><p className="eyebrow">Search Himachal</p><h1 className="section-title mt-3">Find a journey.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-600">Search by destination, trek, activity, or travel style.</p><form onSubmit={submit} className="mt-8 flex max-w-2xl gap-2"><label className="sr-only" htmlFor="search-page">Search tours</label><Input id="search-page" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search Triund, Bir, Dharamshala or a trip type" className="h-12 rounded-md" /><button className="focus-ring inline-flex h-12 shrink-0 items-center gap-2 rounded-md bg-[#123d5b] px-5 text-xs font-extrabold uppercase tracking-[.1em] text-white"><Search className="size-4" /> Search</button></form>{submitted && <div className="mt-12"><p className="text-sm text-slate-500">{isFetching ? "Searching…" : `Results for “${submitted}”`}</p><div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data?.tours.map(tour => <TourCard key={tour.id} tour={tour} />)}</div>{!isFetching && data && data.tours.length === 0 && <div className="mt-8 border border-[#dfe8e8] bg-[#eef4f2] p-8 text-sm leading-6 text-slate-600">No exact match yet. Try “Dharamshala”, “trek”, “culture”, or “Bir”.</div>}</div>}</section></PublicLayout>; }
