import PublicLayout from "@/components/PublicLayout";
import TourCard from "@/components/TourCard";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Search } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useSearch } from "wouter";

export default function SearchPage() { const search = useSearch(); const initial = new URLSearchParams(search).get("q") || ""; const [query, setQuery] = useState(initial); const [submitted, setSubmitted] = useState(initial); const { data, isFetching } = trpc.tours.search.useQuery({ query: submitted || "__" }, { enabled: submitted.trim().length >= 2 }); function submit(e: FormEvent) { e.preventDefault(); setSubmitted(query.trim()); } return <PublicLayout><section className="container py-14 sm:py-20"><p className="eyebrow">Search the range</p><h1 className="section-title mt-3">Find a journey.</h1><form onSubmit={submit} className="mt-8 flex max-w-2xl gap-2"><label className="sr-only" htmlFor="search-page">Search tours and field notes</label><Input id="search-page" value={query} onChange={e => setQuery(e.target.value)} placeholder="Triund, culture, Bir…" className="h-12 rounded-xl" /><button className="focus-ring inline-flex h-12 shrink-0 items-center gap-2 rounded-xl bg-[#123d5b] px-5 text-xs font-extrabold uppercase tracking-[.1em] text-white"><Search className="size-4" /> Search</button></form>{submitted && <div className="mt-12"><p className="text-sm text-slate-500">{isFetching ? "Searching…" : `Results for “${submitted}”`}</p><div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data?.tours.map(tour => <TourCard key={tour.id} tour={tour} />)}</div>{data?.blogs.length ? <div className="mt-12"><h2 className="display text-3xl font-bold text-[#123d5b]">Field notes</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{data.blogs.map(blog => <Link key={blog.id} href={`/blog/${blog.slug}`} className="rounded-2xl border border-[#dfe8e8] bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-lg"><p className="text-xs font-extrabold uppercase tracking-[.1em] text-[#e17818]">Field note</p><h3 className="display mt-3 text-3xl font-bold text-[#123d5b]">{blog.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{blog.excerpt}</p></Link>)}</div></div> : null}{!isFetching && data && data.tours.length + data.blogs.length === 0 && <div className="mt-8 rounded-2xl bg-[#eef4f2] p-8 text-sm text-slate-600">No exact match yet. Try “Dharamshala”, “trek”, or “Bir”.</div>}</div>}</section></PublicLayout>; }
