import PublicLayout from "@/components/PublicLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ChevronLeft, Send } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useRoute } from "wouter";

export default function TourBooking() {
  const [, params] = useRoute("/book/:slug");
  const { data: tour } = trpc.tours.bySlug.useQuery({ slug: params?.slug ?? "" }, { enabled: Boolean(params?.slug) });
  const booking = trpc.bookings.create.useMutation();
  const [done, setDone] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); booking.mutate({ tourId: tour?.id, tourTitle: tour?.title || "Custom trip request", guestName: String(data.get("name")), email: String(data.get("email")), phone: String(data.get("phone")), travelDate: String(data.get("date")) || undefined, travellers: Number(data.get("travellers")), message: String(data.get("message")) || undefined }, { onSuccess: () => setDone(true) }); }
  return <PublicLayout>
    <section className="border-b border-[#254f68] bg-[#123d5b] py-14 text-white sm:py-18"><div className="container"><Link href={tour ? `/tours/${tour.slug}` : "/tours"} className="focus-ring inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.1em] text-white/76 hover:text-white"><ChevronLeft className="size-4" /> Back to journey</Link><p className="mt-8 text-[.7rem] font-extrabold uppercase tracking-[.16em] text-[#f39a48]">Start with a request</p><h1 className="display mt-3 text-[clamp(2.4rem,5vw,4rem)] font-bold leading-none">{tour?.title || "Plan your trip"}</h1></div></section>
    <section className="container max-w-4xl py-12 sm:py-16">{done ? <div className="border border-[#cfe6d8] bg-[#f2fbf4] p-8 text-center"><CheckCircle2 className="mx-auto size-12 text-[#2d9b61]" /><h2 className="display mt-5 text-4xl font-bold text-[#123d5b]">Request received.</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-slate-600">Thank you. We have your details for {tour?.title || "your trip"}. The team will review your plan and come back to you directly.</p><Link href="/tours" className="focus-ring mt-6 inline-flex bg-[#123d5b] px-5 py-3 text-xs font-extrabold uppercase tracking-[.1em] text-white">Explore more journeys</Link></div> : <form onSubmit={submit} className="border border-[#dfe8e8] bg-white p-6 sm:p-8"><div className="mb-7 border-b-2 border-[#e9781c] pb-4"><h2 className="display text-3xl font-bold text-[#123d5b]">Plan this journey</h2><p className="mt-2 text-sm leading-6 text-slate-500">Add your travel details. Trip Himalaya confirms availability before anything is final.</p></div><div className="grid gap-5 sm:grid-cols-2"><FormField label="Your name" name="name" required /><FormField label="Email address" name="email" type="email" required /><FormField label="Phone / WhatsApp" name="phone" required /><div><Label htmlFor="travellers">Number of travellers</Label><Input id="travellers" className="mt-2 h-11 rounded-none border-[#ccd9d7]" name="travellers" type="number" min="1" defaultValue="2" required /></div><div className="sm:col-span-2"><Label htmlFor="date">Preferred travel date</Label><Input id="date" className="mt-2 h-11 rounded-none border-[#ccd9d7]" name="date" type="date" /></div><div className="sm:col-span-2"><Label htmlFor="message">What should we know?</Label><Textarea id="message" className="mt-2 min-h-28 rounded-none border-[#ccd9d7]" name="message" placeholder="For example: fitness level, a celebration, children in the group, or any question." /></div></div><Button disabled={booking.isPending} className="mt-7 h-12 w-full rounded-none bg-[#e9781c] text-xs font-extrabold uppercase tracking-[.1em] hover:bg-[#d86b12]">{booking.isPending ? "Sending request…" : <><Send className="size-4" /> Send tour request</>}</Button>{booking.error && <p className="mt-3 text-sm text-red-600">We could not send your request. Please try again.</p>}</form>}</section>
  </PublicLayout>;
}
function FormField({ label, name, type = "text", required = false }: { label: string; name: string; type?: string; required?: boolean }) { return <div><Label htmlFor={name}>{label}</Label><Input id={name} name={name} className="mt-2 h-11 rounded-none border-[#ccd9d7]" type={type} required={required} /></div>; }
