import PublicLayout from "@/components/PublicLayout";
import TourCard from "@/components/TourCard";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Loader2, Mountain } from "lucide-react";
import { Link } from "wouter";

export default function Treks() {
  const { data: tours = [], isLoading, isError, refetch } = trpc.tours.list.useQuery(undefined, { retry: false });
  const treks = tours.filter(tour => tour.category.toLowerCase().includes("trek"));
  return <PublicLayout><section className="border-b border-[#dfe8e8] bg-[#123d5b] py-16 text-white sm:py-20"><div className="container grid gap-6 lg:grid-cols-[1fr_.58fr] lg:items-end"><div><p className="eyebrow !text-[#f39a48]">Guided treks</p><h1 className="section-title mt-3 !text-white">Trek with the route and pace in mind.</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/75">From first Himalayan walks to longer lake trails, we help you choose a trek that suits your dates, group and comfort level.</p></div><Link href="/contact" className="focus-ring inline-flex h-11 items-center justify-center gap-2 border border-white/35 bg-white/10 px-4 text-sm font-bold text-white hover:bg-white/18 lg:justify-self-end">Ask about a trek <ArrowRight className="size-4" /></Link></div></section><section className="container py-14 sm:py-18"><div className="mb-8 flex items-center gap-3 border-b border-[#dfe8e8] pb-5"><span className="grid size-9 place-items-center border border-[#d7e3de] bg-[#f8fbf9] text-[#e17818]"><Mountain className="size-4" /></span><p className="text-sm font-semibold text-slate-600">Clear route notes before you book: season, effort, duration and what to bring.</p></div>{isLoading ? <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#e17818]" /><span className="sr-only">Loading treks</span></div> : isError ? <div className="border border-[#dfe8e8] bg-[#eef4f2] p-8 text-center"><p className="font-semibold text-[#123d5b]">We could not load treks right now.</p><button onClick={() => void refetch()} className="focus-ring mt-4 bg-[#123d5b] px-5 py-2 text-xs font-bold text-white">Try again</button></div> : treks.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{treks.map(tour => <TourCard key={tour.id} tour={tour} />)}</div> : <div className="border border-dashed border-[#ccd9d7] p-12 text-center text-sm text-slate-500">Fresh trekking routes are being prepared for the next mountain season.</div>}</section></PublicLayout>;
}
