import PublicLayout from "@/components/PublicLayout";
import TourCard from "@/components/TourCard";
import { trpc } from "@/lib/trpc";
import { Loader2, Mountain } from "lucide-react";

export default function Treks() {
  const { data: tours = [], isLoading, isError, refetch } = trpc.tours.list.useQuery(undefined, { retry: false });
  const treks = tours.filter(tour => tour.category.toLowerCase().includes("trek"));
  return <PublicLayout><section className="relative overflow-hidden bg-[#123d5b] py-20 text-white"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_15%_15%,#e9781c_0,transparent_30%),radial-gradient(circle_at_80%_90%,#4da7b8_0,transparent_35%)]" /><div className="container relative"><p className="eyebrow !text-[#f39a48]">Himalayan trekking</p><h1 className="display mt-4 max-w-3xl text-[clamp(3.5rem,8vw,6.5rem)] font-bold leading-[.8]">Find your<br /><span className="text-[#f39a48]">next ridge.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/75">Guided hikes and treks around Dharamshala, paced with local knowledge and respect for mountain conditions.</p></div></section><section className="container py-14 sm:py-18"><div className="mb-8 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#eef4f2] text-[#e17818]"><Mountain className="size-5" /></span><p className="text-sm font-semibold text-slate-500">From gentle first trails to longer lake routes.</p></div>{isLoading ? <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#e17818]" /><span className="sr-only">Loading treks</span></div> : isError ? <div className="rounded-2xl bg-[#eef4f2] p-8 text-center"><p className="font-semibold text-[#123d5b]">We could not load treks right now.</p><button onClick={() => void refetch()} className="focus-ring mt-4 rounded-full bg-[#123d5b] px-5 py-2 text-xs font-bold text-white">Try again</button></div> : treks.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{treks.map(tour => <TourCard key={tour.id} tour={tour} />)}</div> : <div className="rounded-2xl border border-dashed border-[#ccd9d7] p-12 text-center text-sm text-slate-500">Fresh trekking routes are being prepared for the next mountain season.</div>}</section></PublicLayout>;
}
