import PublicLayout from "@/components/PublicLayout";
import TourCard from "@/components/TourCard";
import { getImageVariant } from "@/lib/imageDelivery";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Loader2, Mountain } from "lucide-react";
import { Link } from "wouter";

export default function Treks() {
  const { data: tours = [], isLoading, isError, refetch } = trpc.tours.list.useQuery(undefined, { retry: false });
  const treks = tours.filter(tour => tour.category.toLowerCase().includes("trek"));
  return <PublicLayout><section className="relative isolate overflow-hidden border-b border-[#254f68] text-white"><img src={getImageVariant("/manus-storage/triund-trek-unsplash_2dd49872.jpg", "hero")} alt="Himalayan trekking landscape" className="absolute inset-0 -z-20 h-full w-full object-cover" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(6,42,70,.92),rgba(6,42,70,.58),rgba(6,42,70,.38))]" /><div className="container grid gap-6 py-18 sm:py-24 lg:grid-cols-[1fr_.58fr] lg:items-end"><div><p className="text-[.7rem] font-extrabold uppercase tracking-[.16em] text-[#f39a48]">Guided treks</p><h1 className="display mt-3 max-w-2xl text-[clamp(2.8rem,5.6vw,4.8rem)] font-bold leading-[.9]">Trek with the route and pace in mind.</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/78">From first Himalayan walks to longer lake trails, choose a trek that suits your dates, group, and comfort level.</p></div><Link href="/contact" className="focus-ring inline-flex h-11 items-center justify-center gap-2 border border-white/45 bg-white px-5 text-xs font-extrabold uppercase tracking-[.09em] text-[#123d5b] hover:bg-[#eef4f2] lg:justify-self-end">Ask about a trek <ArrowRight className="size-4" /></Link></div></section><section className="container py-10 sm:py-14"><div className="mb-9 flex items-center gap-3 border-y border-[#dfe8e8] py-4"><Mountain className="size-5 text-[#e9781c]" /><p className="text-sm font-semibold text-[#123d5b]">Clear route notes before you book: season, effort, duration, and what to bring.</p></div>{isLoading ? <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#e17818]" /><span className="sr-only">Loading treks</span></div> : isError ? <div className="border border-[#dfe8e8] bg-[#eef4f2] p-8 text-center"><p className="font-semibold text-[#123d5b]">We could not load treks right now.</p><button onClick={() => void refetch()} className="focus-ring mt-4 bg-[#123d5b] px-5 py-2 text-xs font-bold text-white">Try again</button></div> : treks.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{treks.map(tour => <TourCard key={tour.id} tour={tour} />)}</div> : <div className="border border-dashed border-[#ccd9d7] p-12 text-center text-sm text-slate-500">Fresh trekking routes are being prepared for the next mountain season.</div>}</section></PublicLayout>;
}
