-- Trip Himalaya: requested tour-name drafts
-- SAFE BY DEFAULT:
--   * INSERT IGNORE avoids changing an existing row with the same slug.
--   * isPublished and isFeatured remain FALSE.
--   * Replace the placeholder fields in Admin Portal before publishing.
--   * This script is provided for manual review; it has not been executed by Trip Himalaya.

INSERT IGNORE INTO `tours`
(`title`, `slug`, `category`, `location`, `duration`, `difficulty`, `priceFrom`, `heroImage`, `gallery`, `shortDescription`, `overview`, `highlights`, `itinerary`, `inclusions`, `exclusions`, `isPublished`, `isFeatured`, `isBestSeller`, `featureOrder`)
VALUES
('Lamdal Trek', 'lamdal-trek', 'Trekking', 'Dharamshala, Himachal Pradesh', 'To be confirmed', 'To be confirmed', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed Lamdal Trek details.', 'Draft content — add the verified route, dates, safety information, and itinerary in Admin Portal before publishing.', JSON_ARRAY('Add verified highlights in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed itinerary.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Baleni Pass', 'baleni-pass', 'Trekking', 'Himachal Pradesh', 'To be confirmed', 'To be confirmed', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed Baleni Pass details.', 'Draft content — add the verified route, dates, safety information, and itinerary in Admin Portal before publishing.', JSON_ARRAY('Add verified highlights in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed itinerary.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Minkiani Pass', 'minkiani-pass', 'Trekking', 'Dharamshala, Himachal Pradesh', 'To be confirmed', 'To be confirmed', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed Minkiani Pass details.', 'Draft content — add the verified route, dates, safety information, and itinerary in Admin Portal before publishing.', JSON_ARRAY('Add verified highlights in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed itinerary.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Seven Lake Trek', 'seven-lake-trek', 'Trekking', 'Dharamshala, Himachal Pradesh', 'To be confirmed', 'To be confirmed', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed Seven Lake Trek details.', 'Draft content — add the verified route, dates, safety information, and itinerary in Admin Portal before publishing.', JSON_ARRAY('Add verified highlights in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed itinerary.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Dharamshala Tour', 'dharamshala-tour', 'Tour', 'Dharamshala, Himachal Pradesh', 'To be confirmed', 'Easy', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed Dharamshala Tour details.', 'Draft content — add the verified places, dates, inclusions, and itinerary in Admin Portal before publishing.', JSON_ARRAY('Add verified highlights in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed itinerary.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Five Devi Darshan in Himachal', 'five-devi-darshan-himachal', 'Tour', 'Himachal Pradesh', 'To be confirmed', 'Easy', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed Five Devi Darshan details.', 'Draft content — add the verified temples, dates, travel plan, and itinerary in Admin Portal before publishing.', JSON_ARRAY('Add verified highlights in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed itinerary.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Manali Tour', 'manali-tour', 'Tour', 'Manali, Himachal Pradesh', 'To be confirmed', 'Easy', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed Manali Tour details.', 'Draft content — add the verified places, dates, travel plan, and itinerary in Admin Portal before publishing.', JSON_ARRAY('Add verified highlights in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed itinerary.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Dalhousie - Chamba', 'dalhousie-chamba', 'Tour', 'Dalhousie and Chamba, Himachal Pradesh', 'To be confirmed', 'Easy', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed Dalhousie–Chamba details.', 'Draft content — add the verified places, dates, travel plan, and itinerary in Admin Portal before publishing.', JSON_ARRAY('Add verified highlights in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed itinerary.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Paragliding', 'paragliding', 'Adventure', 'Himachal Pradesh', 'To be confirmed', 'To be confirmed', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed paragliding details.', 'Draft content — add the verified operator, location, season, safety information, and booking details in Admin Portal before publishing.', JSON_ARRAY('Add verified activity details in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed activity plan.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Zipline', 'zipline', 'Adventure', 'Himachal Pradesh', 'To be confirmed', 'To be confirmed', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed zipline details.', 'Draft content — add the verified operator, location, season, safety information, and booking details in Admin Portal before publishing.', JSON_ARRAY('Add verified activity details in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed activity plan.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('ATV Ride', 'atv-ride', 'Adventure', 'Himachal Pradesh', 'To be confirmed', 'To be confirmed', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed ATV ride details.', 'Draft content — add the verified operator, location, season, safety information, and booking details in Admin Portal before publishing.', JSON_ARRAY('Add verified activity details in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed activity plan.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Jeep Safari', 'jeep-safari', 'Adventure', 'Himachal Pradesh', 'To be confirmed', 'To be confirmed', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed Jeep Safari details.', 'Draft content — add the verified operator, location, season, safety information, and booking details in Admin Portal before publishing.', JSON_ARRAY('Add verified activity details in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed activity plan.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Sky Cycling', 'sky-cycling', 'Adventure', 'Himachal Pradesh', 'To be confirmed', 'To be confirmed', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed sky cycling details.', 'Draft content — add the verified operator, location, season, safety information, and booking details in Admin Portal before publishing.', JSON_ARRAY('Add verified activity details in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed activity plan.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Riverside Picnic', 'riverside-picnic', 'Adventure', 'Himachal Pradesh', 'To be confirmed', 'Easy', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed riverside picnic details.', 'Draft content — add the verified location, access notes, season, safety information, and booking details in Admin Portal before publishing.', JSON_ARRAY('Add verified activity details in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed activity plan.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Kareri Village Tour', 'kareri-village-tour', 'Local & Culture', 'Kareri, Himachal Pradesh', 'To be confirmed', 'Easy', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed Kareri Village Tour details.', 'Draft content — add the verified local experiences, access notes, dates, and itinerary in Admin Portal before publishing.', JSON_ARRAY('Add verified highlights in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed itinerary.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0),
('Boh Village Tour', 'boh-village-tour', 'Local & Culture', 'Boh Valley, Himachal Pradesh', 'To be confirmed', 'Easy', 0, '', JSON_ARRAY(), 'Draft listing — replace with the confirmed Boh Village Tour details.', 'Draft content — add the verified local experiences, access notes, dates, and itinerary in Admin Portal before publishing.', JSON_ARRAY('Add verified highlights in Admin Portal'), JSON_ARRAY(JSON_OBJECT('day', '1', 'title', 'Details to be added', 'description', 'Replace with the confirmed itinerary.')), JSON_ARRAY('To be confirmed'), JSON_ARRAY('To be confirmed'), FALSE, FALSE, FALSE, 0);

-- Review before making anything public:
-- SELECT id, title, slug, category, isPublished, isFeatured FROM tours
-- WHERE slug IN ('lamdal-trek','baleni-pass','minkiani-pass','seven-lake-trek','dharamshala-tour','five-devi-darshan-himachal','manali-tour','dalhousie-chamba','paragliding','zipline','atv-ride','jeep-safari','sky-cycling','riverside-picnic','kareri-village-tour','boh-village-tour');
